#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ def feature_gates():
#@   gates = {} 
#@   if data.values.KUBEADM_FEATURE_GATES:
#@     for gate in data.values.KUBEADM_FEATURE_GATES:
#@       gates.update({ gate: True})
#@     end
#@   end
#@   return gates
#@ end

#@overlay/match by=overlay.subset({"kind":"KubeadmConfigTemplate"}),expects="1+"
#@overlay/match-child-defaults missing_ok=True
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: #@ "{}-md-0".format(data.values.CLUSTER_NAME)
spec:
  template:
     spec:
       clusterConfiguration:
         featureGates: #@ feature_gates()
