ip: 10.18.1.231
host: avi.lab.shortrib.net
mask: 24

vsphere:
  datacenter: garage
  pool: tanzu
  datastore: vsanDatastore
  network: management-pg

image: /home/crdant/share/images/controller-21.1.3-9051.ova 
ssh:
  public: /home/crdant/.ssh/id_homelab.pub

